name: active_days
description: Helps to caculate how many days has a user been active in a week.
version: 0.0.1
author: Weizhong Yang <zonble@gmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
